version: "3.6"
services:
 registry:
   image: registry
   networks:
    - isolated_nw
 user-service:
   image: userservice
   ports:
    - 9001:9001
   networks:
    - isolated_nw
 userdb:
   image: mysql:latest
   container_name: userdb
   ports:
    - "3306:3306"
   restart: on-failure
   volumes:
    -  mysqldatavolume:/var/lib/mysql
   environment:
    - MYSQL_ROOT_PASSWORD=root123
    - MYSQL_USER=root
    - MYSQL_PASSWORD=root123
    - MYSQL_DATABASE=yorbit
   networks:
     isolated_nw:
       ipv4_address: 172.25.3.3
volumes:
  mysqldatavolume: 
    external:
      name: mysqldatavolume
networks:
  isolated_nw:
    external:
      name: isolated_nw
      
